# Generated by Django 5.2.4 on 2025-08-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('academy', 'plan_type')},
        ),
    ]
