# Generated by Django for seeding PlanType values
from django.db import migrations


def seed_plan_types(apps, schema_editor):
    PlanType = apps.get_model('payment', 'PlanType')
    for name in ['Starter', 'Professional', 'Enterprise']:
        PlanType.objects.get_or_create(name=name)


def unseed_plan_types(apps, schema_editor):
    PlanType = apps.get_model('payment', 'PlanType')
    PlanType.objects.filter(name__in=['Starter', 'Professional', 'Enterprise']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_subscriptionplan_unique_together'),
    ]

    operations = [
        migrations.RunPython(seed_plan_types, reverse_code=unseed_plan_types),
    ]
