# Generated by Django 5.2.4 on 2025-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_seed_plan_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantype',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantype',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plantype',
            name='icon_class',
            field=models.CharField(default='bi-app', max_length=50),
        ),
        migrations.AddField(
            model_name='plantype',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantype',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
