# Generated by Django 5.2.5 on 2025-09-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_subscriptionplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantype',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
