# Generated by Django 5.2.5 on 2025-09-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, blank=True),
        ),
    ]

