# Generated by Django 5.2.5 on 2025-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='children', to='academies.program'),
        ),
    ]
