# Generated by Django 5.2.5 on 2025-09-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_add_emergency_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='programs',
        ),
    ]
