# Generated by Django 5.2.5 on 2025-09-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0011_session_enrolled'),
        ('parents', '0003_remove_child_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='academies.session'),
        ),
    ]
