# Generated by Django 5.2.5 on 2025-08-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_enrollments', to='parents.child'),
        ),
    ]
