# Generated by Django 5.2.5 on 2025-09-02 14:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0004_alter_child_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/do1wotvij/image/upload/v1699999999/Majd/children/profile_images/default_profile.webp",
                max_length=255,
                verbose_name="profile_image",
            ),
        ),
    ]
