# Generated by Django 5.2.5 on 2025-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_alter_enrollment_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='emergency_contact_phone',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
