# Generated by Django 5.2.4 on 2025-09-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parents", "0004_enrollment_sessions"),
        ("parents", "0005_alter_child_profile_image"),
    ]

    operations = []
