# Generated by Django 5.2.5 on 2025-09-03 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0015_merge_20250903_0248'),
        ('accounts', '0007_merge_20250903_0247'),
        ('parents', '0006_merge_20250903_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(default='monthly', max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_subscriptions', to='academies.academy')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.parentprofile')),
            ],
            options={
                'unique_together': {('parent', 'academy')},
            },
        ),
    ]
