# Generated by Django 5.2.5 on 2025-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_parentsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('paid', 'Paid'), ('pending', 'Pending')], default='not_paid', max_length=20),
        ),
    ]
