# Generated by Django 5.2.5 on 2025-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0013_alter_academy_cover_alter_academy_logo_and_more'),
        ('parents', '0007_enrollment_payment_date_enrollment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='enrollments', to='academies.session'),
        ),
    ]
