# Generated by Django 5.2.5 on 2025-09-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_merge_20250903_0336'),
        ('parents', '0006_merge_20250903_1111'),
        ('parents', '0008_alter_enrollment_sessions'),
        ('parents', '0008_enrollment_payment_date_enrollment_payment_status'),
    ]

    operations = [
    ]
