# Generated by Django 5.2.5 on 2025-08-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='trainerprofile',
        #     name='academy',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='academies.academy'),
        # ),
    ]
