# Generated by Django 5.2.4 on 2025-08-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0005_delete_subscriptionplan'),
        ('accounts', '0002_trainerprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='academies.academy'),
        ),
    ]
