# Generated by Django 5.2.5 on 2025-08-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trainerprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
