# Generated by Django 5.2.5 on 2025-08-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academies",
            "0007_remove_session_end_date_remove_session_start_date_and_more",
        ),
        ("accounts", "0002_trainerprofile_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerprofile",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainers",
                to="academies.academy",
            ),
        ),
    ]
