# Generated by Django 5.2.5 on 2025-08-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_trainerprofile_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name": "Child", "verbose_name_plural": "Children"},
        ),
    ]
