# Generated by Django 5.2.5 on 2025-08-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_trainerprofile_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
