# Generated by Django 5.2.5 on 2025-08-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_sessionslot_weekday_trainingclass"),
        ("accounts", "0004_alter_child_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerprofile",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainers",
                to="academies.academy",
            ),
        ),
    ]
