# Generated by Django 5.2.5 on 2025-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_trainerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Academy approval status required for dashboard access.', max_length=10),
        ),
    ]
