# Generated by Django 5.2.5 on 2025-09-02 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_trainerprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerprofile",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/do1wotvij/image/upload/v1699999999/Majd/trainers/profile_images/profileImage.webp",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
