# Generated by Django 5.2.5 on 2025-09-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_trainerprofile_approval_status'),
        ('accounts', '0006_alter_trainerprofile_profile_image'),
    ]

    operations = [
    ]
