# Generated by Django 5.2.5 on 2025-09-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20250903_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('NotRegistered', 'Not Registered')], default='NotRegistered', help_text='Academy approval status required for dashboard access.', max_length=50),
        ),
    ]
