# Generated by Django 5.2.5 on 2025-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_trainerprofile_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
