# Generated by Django 5.2.5 on 2025-08-26 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('accounts', '0004_delete_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_academies', to='accounts.academyadminprofile'),
        ),
    ]
