# Generated by Django 5.2.5 on 2025-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="short_description",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
