# Generated by Django 5.2.5 on 2025-08-27 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_plantype_academy_slug_subscriptionplan'),
        ('accounts', '0002_trainerprofile_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy', to='accounts.academyadminprofile'),
        ),
    ]
