# Generated by Django 5.2.5 on 2025-08-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_alter_academy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
    ]
