# Generated by Django 5.2.5 on 2025-08-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0004_alter_academy_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
