# Generated by Django 5.2.5 on 2025-08-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0002_alter_program_short_description"),
        ("academies", "0005_delete_subscriptionplan"),
    ]

    operations = []
