# Generated by Django 5.2.5 on 2025-08-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academies",
            "0007_remove_session_end_date_remove_session_start_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs",
                to="academies.academy",
            ),
        ),
    ]
