# Generated by Django 5.2.5 on 2025-08-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0006_merge_20250830_2009'),
        ('academies', '0009_position_skilldefinition_sessionskill'),
    ]

    operations = [
    ]
