# Generated by Django 5.2.5 on 2025-08-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0010_merge_20250831_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
