# Generated by Django 5.2.5 on 2025-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0011_session_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='mission',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
