# Generated by Django 5.2.5 on 2025-09-02 14:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0012_alter_academy_cover_alter_academy_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="cover",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cover"
            ),
        ),
        migrations.AlterField(
            model_name="academy",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="logo"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="program"
            ),
        ),
    ]
