# Generated by Django 5.2.5 on 2025-09-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0012_academy_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
