# Generated by Django 5.2.5 on 2025-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0013_academy_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
