# Generated by Django 5.2.5 on 2025-09-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0013_alter_academy_cover_alter_academy_logo_and_more'),
        ('academies', '0014_alter_academy_email'),
    ]

    operations = [
    ]
