# Generated by Django 5.2.5 on 2025-08-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_alter_enrollment_child'),
        ('player_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerenrollment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_enrollments', to='parents.child'),
        ),
    ]
