# Generated by Django 5.2.5 on 2025-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerskill",
            name="target_level",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
