# Generated by Django 5.2.5 on 2025-08-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0009_position_skilldefinition_sessionskill"),
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="academies.position",
            ),
        ),
    ]
