# Generated by Django 5.2.5 on 2025-08-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_playerskill_target_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="program_name",
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="player.trainingprogram",
            ),
        ),
    ]
