# Generated by Django 5.2.5 on 2025-08-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academies", "0001_initial"),
        ("accounts", "0004_alter_child_options"),
        ("player", "0005_evaluation_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingsession",
            name="program",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="coach",
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluations",
                to="academies.session",
            ),
        ),
        migrations.AlterField(
            model_name="playersession",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="academies.session",
            ),
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="academy_name",
        ),
        migrations.AddField(
            model_name="evaluation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="performance_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="skill_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="academy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="academies.academy",
            ),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="players",
                to="accounts.trainerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="playersession",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                ],
                default="present",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="TrainingProgram",
        ),
        migrations.DeleteModel(
            name="TrainingSession",
        ),
    ]
